config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'blogtexts#index';
  resources :blogtexts do
    resources :comments, only: [:new, :create]
  end
  resources :users, only: [:update, :edit, :index, :show] do
    resources :blogtexts, only: [:show, :destroy]
  end
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogtext.rb
class Blogtext < ApplicationRecord

  validates_presence_of :title, :text
  # validates :title,    length: { maximum: 12 }
  belongs_to  :user
  has_many    :comments
  
end

app/models/comment.rb
class Comment < ApplicationRecord

  # validates_presence_of :comment
  validates :comment, presence: true
  belongs_to  :user
  belongs_to  :blogtext

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many  :blogtexts
  has_many  :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/blogtexts_controller.rb
class BlogtextsController < ApplicationController
  before_action :set_bloglists, only: [:new, :show, :index, :edit]

  def new
    @blogtext = Blogtext.new
  end

  def create
    Blogtext.create(title: blogtext_params[:title], text: blogtext_params[:text], user_id: current_user.id)
    redirect_to action: :index
  end

  def show
    @blogtext = Blogtext.find(params[:id])
    @comment = Comment.new
    @comments = @blogtext.comments.includes(:user)
  end

  def index
    @blogtext = Blogtext.order("created_at DESC").find_by(params[:id])
  end

  def destroy
    blogtext = Blogtext.find(params[:id])
    if blogtext.user_id == current_user.id
      blogtext.destroy
      redirect_to users_path(current_user.id)
    end
      
  end

  def update
    blogtext = Blogtext.find(params[:id])
    if blogtext.user_id == current_user.id
      blogtext.update(blogtext_params)
    end
    redirect_to action: :show
  end

  def edit
    @blogtext = Blogtext.find(params[:id])
  end

  private
  def blogtext_params
    params.require(:blogtext).permit(:title, :text)
  end

  def set_bloglists
    @blogtexts = Blogtext.includes(:user).order("created_at DESC")
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :comment_params, only: [:new, :create]
  before_action :set_blogtext, only: [:create]

  def new
  end

  def create
    # Comment.create(comment_params)
    @comment = @blogtext.comments.new(comment_params)
    # binding.pry
    if @comment.save
      respond_to do |format|
        format.html { redirect_to blogtext_path(comment_params[:blogtext_id]) }
        format.json
      end
    else
      redirect_to blogtext_path(comment_params[:blogtext_id])
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id)
  end

  def set_blogtext
    @blogtext = Blogtext.find(params[:blogtext_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_userbloglists, only: [:show, :index, :edit, :update]
  
  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
      # render controller: 'blogtexts', action: 'edit'
    end
  end

  def edit
    @blogtext = Blogtext.where(user_id: current_user.id).order("created_at DESC").find_by(params[:id])
  end

  def index
    @blogtext = Blogtext.where(user_id: current_user.id).order("created_at DESC").find_by(params[:id])
  end

  

  def show
    @blogtext = Blogtext.find(params[:id])
    @comment = Comment.new
    @comments = @blogtext.comments.includes(:user)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

  def set_userbloglists
    @blogtexts = Blogtext.where(user_id: current_user.id).order("created_at DESC")
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogtexts/_bloglists.html.haml
%li.middle__info__list
  %p.middle__info__list--time-stamp
    = blogtext.created_at.strftime('%Y年%-m月%-d日(%a)%H時%M分')
  %p.middle__info__list--user-name
    = blogtext.user.name
  %p.middle__info__list--title
    - if newOrUser == "マイブログ記事"
      = link_to blogtext.title, user_path(blogtext.id), method: :get
    - else
      = link_to blogtext.title, blogtext_path(blogtext.id), method: :get
  - if user_signed_in?
    - if blogtext.user_id == current_user.id
      %p.middle__info__list--button
        -# = link_to "編集する", edit_blogtext_path(blogtext.id), method: :get
        = link_to "編集する", edit_user_path(blogtext.id), method: :get
      %p.middle__info__list--button
        = link_to "削除する", blogtext_path(blogtext.id), method: :delete, data: { confirm: "削除しますか？" }
    
    

app/views/blogtexts/_comments.html.haml
- comments.each do |comment|
  %li.comment__user-name
    %span
      = comment.user.name
    .comment__main
      = comment.comment

app/views/blogtexts/_footer-content.html.haml
.footer__content
  .footer__top-scroll
    %a.footer__top-scroll--text ページトップ
    

app/views/blogtexts/_middle-main.html.haml
.middle-main__header
  .middle-main__header__title
    %p
      = blogtext.title
  .middle-main__header__user-info
    %p.middle-main__header--time-stamp 
      投稿日：
      = blogtext.created_at.strftime('%Y年%-m月%-d日(%a)%H時%M分')
    %p.middle-main__header--user-name 
      投稿者：
      = blogtext.user.name
.middle-main__blog
  %h1 本文
.blog__text
  %p 
  = blogtext.text
.middle-main__border

app/views/blogtexts/_middle-side.html.haml
.middle-side
  %p.middle-side__header
    = newOrUser
  
  %ul.middle__info
    - blogtexts.each do |blogtext|
      = render partial: '/blogtexts/bloglists', locals: { blogtext: blogtext, newOrUser: newOrUser }

app/views/blogtexts/edit.html.haml
.middle-content
  = render partial: 'middle-side', locals: { blogtexts: @blogtexts, newOrUser: "新着ブログ記事"  }
  .middle-main    
    .middle-main__blog
      %h1 本文（編集）
    .blog__text
      %p 
        - if @blogtext.user_id == current_user.id
          .form
            = form_for [@blogtext] do |f|
              = f.text_field :title, class: 'form-title'
              = f.submit '更新する', class: 'form-btn'
              = f.text_area :text, class: 'form-text'
        - else
          = @blogtext.text
= render partial: 'footer-content'

app/views/blogtexts/index.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PENPEN-BLOG

  %body
    .middle-content
      = render partial: 'middle-side', locals: { blogtexts: @blogtexts, newOrUser: "新着ブログ記事"  }
    = render partial: 'footer-content'
    

app/views/blogtexts/new.html.haml
.middle-content
  = render partial: 'middle-side', locals: { blogtexts: @blogtexts, newOrUser: "新着ブログ記事"  }
  .middle-main
    .form
      = form_for [@blogtext] do |f|
        = f.text_field :title, class: 'form-title', placeholder: 'タイトルを入力してください' 
        = f.submit '投稿する', class: 'form-btn'
        = f.text_area :text, class: 'form-text'
= render partial: 'footer-content'

app/views/blogtexts/show.html.haml
.middle-content
  = render partial: 'middle-side', locals: { blogtexts: @blogtexts, newOrUser: "新着ブログ記事"  }
  .middle-main    
    = render partial: 'middle-main', locals: { blogtext: @blogtext }
    .middle-main__border 
      .form-comment
        = form_for [@blogtext, @comment] do |f|
          = f.text_area :comment, class: 'form-comment-box'
          = f.submit 'コメントする', class: 'form-comment-btn'
    %ul.middle-main__comment
      <br>コメント一覧
      - if @comments.length != 0
        = render partial: 'comments', locals: { comments: @comments }
      - else 
        <br><br>コメントはありません
= render partial: 'footer-content'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title App006Blog
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .top-header
      %ul.top-nav
        - if user_signed_in?
          %li.top-nav__button
            = link_to "投稿する", new_blogtext_path, method: :get
          %li.top-nav__button
            = link_to "マイページ", users_path(current_user), method: :get
          %li.top-nav__button
            = link_to "トップページ" ,root_path
          %li.top-nav__button
            = link_to "ログアウト", destroy_user_session_path, method: :delete
          %li.top-nav__button
            = link_to "アカウント編集", edit_user_registration_path
        - else
          %li.top-nav__button
            = link_to "ログイン", new_user_session_path
          %li.top-nav__button
            = link_to "新規登録", new_user_registration_path
    .top-content      
      .top-main

    = yield

app/views/users/edit.html.haml
.middle-content
  = render partial: '/blogtexts/middle-side', locals: { blogtexts: @blogtexts, newOrUser: "マイブログ記事"  }
  .middle-main    
    .middle-main__blog
      %h1 本文（編集）
    .blog__text
      %p 
        - if @blogtext.user_id == current_user.id
          .form
            = form_for [@blogtext] do |f|
              = f.text_field :title, class: 'form-title'
              = f.submit '更新する', class: 'form-btn'
              = f.text_area :text, class: 'form-text'
        - else
          = @blogtext.text
= render partial: '/blogtexts/footer-content'

app/views/users/index.html.haml
.middle-content
  - if @blogtexts.length == 0
    .middle-side
      %p.middle-side__header
        記事未投稿
      %ul.middle__info
    .middle-main 
      .middle-main__blog
        %h1 
      .blog__text
        %p 
      .middle-main__border
      %ul.middle-main__comment
  - else
    = render partial: '/blogtexts/middle-side', locals: { blogtexts: @blogtexts, newOrUser: "マイブログ記事"  }    
  
= render partial: '/blogtexts/footer-content'

app/views/users/show.html.haml
.middle-content
  - if @blogtexts.length == 0
    .middle-side
      %p.middle-side__header
        記事未投稿
      %ul.middle__info
    .middle-main 
      .middle-main__blog
        %h1 
      .blog__text
        %p 
      .middle-main__border
      %ul.middle-main__comment
  - else
    = render partial: '/blogtexts/middle-side', locals: { blogtexts: @blogtexts, newOrUser: "マイブログ記事"  }
    .middle-main    
      = render partial: '/blogtexts/middle-main', locals: { blogtext: @blogtext }
      .middle-main__border 
        .form-comment
          = form_for [@blogtext, @comment] do |f|
            = f.text_area :comment, class: 'form-comment-box'
            = f.submit 'コメントする', class: 'form-comment-btn'
      %ul.middle-main__comment
        <br>コメント一覧
        - if @comments.length != 0
          = render partial: '/blogtexts/comments', locals: { comments: @comments }
        - else 
          <br><br>コメントはありません
= render partial: '/blogtexts/footer-content'